// Generated by jextract

package jextract.win32tape;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "loadTape",
        constants$3.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "unloadTape",
        constants$3.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "lockTape",
        constants$3.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "unlockTape",
        constants$3.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_BOOLEAN,
        JAVA_BOOLEAN,
        JAVA_BOOLEAN,
        JAVA_BOOLEAN,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "setTapeDriveParameters",
        constants$4.const$4
    );
}


